export default {
  // 基础信息相关
  '基础信息': 'Basic Info.',
  '基础信息测试': 'Basic Info test',
  'KOL编号': 'KOL Code',
  'KOL名称': 'KOL Name',
  'KOL账号': 'KOL Account',
  '代理商编号': 'Agency Code',
  '代理商名称': ' Agency name',
  '等级': 'Level',
  '联系人': 'Contact Person',
  '联系人电话': 'Contact Phone',
  '联系电话': 'Contact Number',
  '合同开始时间': 'Start Date',
  '合同结束时间': 'End Date',
  '合同到期时间': 'Contract End Date',
  '电子邮箱': 'Email',
  '企业邮箱': 'Corporate Email',
  '授信额度(元)': 'Credit Limit Applied',
  '地址': 'Address',
  '佣金率(%)': 'Commission Rate (%)',
  '状态': 'Status',
  '启用': 'Enable',
  '停用': 'Deactivate',
  '禁用': 'Disable',

  // 开票信息相关
  '开票信息': 'Billing Info',
  '公司名称': 'Company Name',
  '税号': 'Tax Identification Number',
  '单位地址': 'Company Address',
  '电话号码': 'Phone Number',
  '开户银行': 'Opening Bank',
  '银行账户': 'Bank Account',

  // 登录注册相关
  '邮轮KOL票务平台': 'Cruise KOL ticketing system',
  '账号': 'Account',
  '密码': 'Password',
  '确认密码': 'Confirm Password',
  '验证码': 'Verification Code',
  '注册': 'Register',
  '注册中': 'Registering',
  '使用已有账户登录': 'Use Existing Account to Login',
  '系统登录': 'System Login',
  '用户名': 'Username',
  '请输入密码': 'Please enter password',
  '拖动滑块': 'Drag Slider',
  '文字点选': 'Text Selection',
  '短信验证码': 'SMS Verification Code',
  '获取验证码': 'Get Verification Code',
  '后重新获取': 'Resend after',
  '管理员登录': 'Administrator Login',
  '记住密码': 'Remember Password',
  '登录': 'Login',
  '登录中': 'Logging in',
  '重置密码': 'Reset Password',
  '安全风险（强制措施）': 'Security Risk (Mandatory Measures)',
  '新密码': 'New Password',
  '再输一次': 'Re-enter',
  '密码长度至少8位，且不超过16位': 'Password length must be between 8 and 16 characters',
  '满足至少三种组合': 'Meet at least three combinations',
  '大写字母：A, B, C…Z': 'Uppercase Letters: A, B, C…Z',
  '小写字母：a, b, c…z': 'Lowercase Letters: a, b, c…z',
  '数字：0, 1, 2…9': 'Numbers: 0, 1, 2…9',
  '特殊符号：~, !, @, #, $, %, ^': 'Special Symbols: ~, !, @, #, $, %, ^',
  '确认': 'Confirm',
  'NFC登录': 'NFC Login',
  '中文': 'Chinese',
  '英文': 'English',

  // 提示信息
  '提示': ' Prompt',
  '请输入用户名': 'Please enter username',
  '请填写登录信息': 'Please fill in login information',
  '请填写密码信息': 'Please fill in password information',
  '密码不一致，请重新输入': 'Passwords do not match, please re-enter',
  '用户密码长度必须介于 8 和 16 之间,且需满足至少三种组合': 'User password length must be between 8 and 16 characters and meet at least three combinations',
  '不能包含连续3个相同或者连续的字符或数字': 'Cannot contain 3 consecutive identical or sequential characters or numbers',
  '两次输入的密码不一致': 'The passwords entered two times are inconsistent',
  '请输入您的账号': 'Please enter your account',
  '用户账号长度必须介于 2 和 20 之间': 'User account length must be between 2 and 20 characters',
  '请输入您的密码': 'Please enter your password',
  '请再次输入您的密码': 'Please re-enter your password',
  '请输入验证码': 'Please enter verification code',
  '恭喜你': 'Congratulations',
  '您的账号': 'Your Account',
  '注册成功': 'Registration succeeded',
  '系统提示': ' System prompt',

  // 航次相关
  '航次': 'Voyage',
  '航行和营业日期': 'Sailing and operating date',
  '时区': 'Time Zone',
  '船长控制的时区': 'Captain-Controlled Time Zone',
  '测量': 'Measurement',
  'Working hours': 'Working hours',
  '业务量': 'Business Volume',
  '选择航次': 'Select Voyage',
  '暂无航次': 'No Voyage at the Moment',

  // 分销码相关
  '分销码': 'Distribution Code',
  '分销码编号': 'Distribution Code Number',
  '分销码名称': 'Distribution Code Name',
  '分销码信息': 'Distribution Code Information',
  '分销链接': 'Distribution Link',
  '访问次数': 'Visit Count',
  '使用次数': 'Usage Count',
  '转化率': 'Conversion Rate',
  '生效时间范围': 'Effective Time Range',
  '生效开始时间': 'Effective Start Time',
  '生效结束时间': 'Effective End Time',
  '生效开始日期': 'Effective Start Date',
  '生效结束日期': 'Effective End Date',
  '启用状态': 'Active Status',
  '折扣比例': 'Discount Percentage',
  '请输入分销码': 'Please enter distribution code',
  '请输入分销码名称': 'Please enter distribution code name',
  '请输入折扣比例': 'Please enter discount ratio',
  '请选择生效开始时间': 'Please select effective start time',
  '请选择生效结束时间': 'Please select effective end time',
  '请选择生效开始日期': 'Please select effective start date',
  '新增分销码': 'Add New Distribution Code',
  '查看二维码': 'View QR Code',
  '编辑': 'Edit',
  '返回': 'Back',
  '保存': 'Save',

  // 订单相关
  '订单号': 'Order Number',
  '订单编号': 'Order Number',
  '订单总额': 'Total Order Amount',
  '订单状态': 'Order Status',
  '订单类型': 'Order Type',
  '订单基础信息': 'Order Basic Info',
  '下单时间': 'Order Time',
  '总金额': 'Total Amount',
  '已付金额': 'Paid Amount',
  '邮轮': 'Cruise',
  '航线名称': 'Route Name',
  '航次编号': 'Voyage Code',
  '支付状态': 'Payment Status',
  '付款状态': 'Payment Status',
  '退款状态': 'Refund Status',
  '退订状态': 'Refund Status',
  '结算模式': 'Settlement Mode',
  '佣金': 'Commission',
  '舱房等级': ' Cabin level',
  '舱房佣金总额': 'Total Cabin Commission',
  '预订人信息': 'Booking Person Info.',
  '预订人姓名': ' Booker Name',
  '联系方式': 'Contact Info.',
  '预订人邮箱': 'Booker Email',
  '备注': 'Remarks',
  '详情': 'Details',
  '分销信息': 'Distribution Information',
  '基础信息': 'Basic Info.',
  '查看详情': 'View Details',
  '选择邮轮': 'Select Ship',
  '请输入订单编号': 'Please enter order number',
  '申请开始日期': 'Application Start Date',
  '申请截止日期': 'Application End Date',
  '序号': 'No.',
  '操作': 'Action',

  // 支付相关
  '支付': 'Payment',
  '支付节点': 'Payment Milestone',
  '支付/审核时间': 'Payment/Audit Time',
  '支付/抵扣金额': 'Payment/Deduction Amount',
  '交易类型': 'Transaction Type',
  '退款': 'Refund',
  '交易流水号': 'Transaction Serial',
  '交易方式': 'Transaction Method',
  '交易凭证': 'Payment Receipt',
  '查看': 'View',
  '支付/审核状态': 'Payment/Audit Status',
  '创建时间': 'Created time',
  '当前节点应付金额': 'Amount Due at Current Stage',
  '船票应付总金额': 'Total Ticket Amount Due',
  '附加产品总价': 'Total Add-on Product Price',
  '总应付金额': ' Total Amount Due',
  'FOC减免': 'FOC Reduction',
  '原始舱房费': 'Original Cabin Fee',
  '更名费用': 'Name Change Fee',
  '手续费': 'Penalty Fee',
  '房间数': 'Number of Rooms',
  '人数': 'Headcount',
  '值船人数': 'Check-in Count',
  '下一支付节点': 'Next Payment Node',
  '发票状态': 'Invoice Status',
  '取消订单': 'Cancel Order',
  '导出船票': 'Export Ticket',
  '导出对账单': 'Export Statement',
  '请选择语言版本': 'Please select language version',
  '是否取消订单?': 'Cancel Order?',
  '取消成功': 'Cancelled successfully',

  // 预订相关
  '前往预订': 'Go to Booking',
  '当前航次': 'Current Voyage',
  '已预定铺数': 'Number of Booked Berths',
  '当前可用foc数': 'Current Available FOC Count',
  'FOC条件:': 'FOC Conditions:',
  '满': ' Meet',
  '免': 'Exempt',
  '最大入住人数': 'Maximum occupancy',
  '指导均价': 'Reference Price',
  '按房间': 'By room',
  '按铺位': 'By berth',
  '库存': ' Inventory',
  '数量': 'Quantity',
  '请选择航次': 'Please select voyage',
  '请选择舱房': ' Please select cabin',

  // 旅客乘客相关
  '旅客名称': 'Traveler Name',
  '英文名称': 'English Name',
  '性别': 'Gender',
  '生日': 'Date of Birth',
  '证件类型1': 'ID Type 1',
  '证件号': 'ID Number',
  '铺型': 'Berth Type',
  '值船状态': 'Check-in Status',
  '信息修改申请': 'Information Modification Application',
  '申请中': 'Pending',
  '编辑信息': 'Edit Information',
  '乘客账单': 'Passenger Bill',
  '折扣比例(%)': 'Discount Percentage (%)',
  '确定': 'Confirm',
  '取消': 'Cancel',
  '下发填写链接': 'Send Filling Link',
  '推送模板': 'Push Template',
  '默认语言': 'Default Language',
  '推送方式': 'Push Method',
  '新增乘客': 'New Passenger',
  '编辑乘客': 'Edit Passenger',
  '更新乘客': 'Update Passenger',
  '新增旅客': 'New Traveler',
  '导出人员信息': 'Export Passenger Info',
  '批量更新乘客': 'Bulk Update Passengers',
  '拿舱编号': 'Allocation Code',
  '姓名(中文)': 'Name (Chinese)',
  '姓名(英文)': 'Name (English)',
  '申请号': 'Application Number',
  '申请时间': 'Application Time',
  '申请状态': 'Application Status',
  '退订申请号': 'Cancellation Application Number',
  '查看退订详情': 'View Cancellation Details',
  '退订申请详情': 'Cancellation Application Details',
  '退款申请详情': 'Refund Application Details',
  '退款申请': 'Refund Application',
  '退款金额': 'Refund Amount',
  '退票数': 'Refund Qty',
  '附加服务数': 'Number of Additional Services',
  '退订服务数': 'Number of Cancelled Services',

  // 账单相关
  '授信额度': 'Credit Limit',
  '时间范围': 'Time Range',
  '交易类型': 'Transaction Type',
  '新建申请': 'Create New Application',
  '申请单号': 'Application No',
  '申请授信额度': 'Credit Limit Applied',
  '付款凭证': 'Payment Receipt',
  '发票申请': 'Invoice Application',
  '温馨提示': 'Friendly Reminder',
  '在搜索栏中可使用快捷键': 'Shortcuts can be used in the search bar',
  '搜索': 'Search',
  '订单基础信息': 'Order Basic Info',
  '代理商': 'Agency',
  '舱房信息': 'Cabin Info',
  '舱房号': 'Cabin Number.',
  '舱房价格': 'Cabin Price',
  '需付金额': 'Amount Due',
  '附加产品信息': 'Add-on Product Info.',
  '产品类型': 'Product Type',
  '产品名称': 'Product Name',
  '产品数量': 'Product Quantity',
  '产品总额': 'Total Product Amount',
  '增加费用项': 'Add Fee Item',
  '费用项名称': 'Fee Item Name',
  '费用金额': 'Fee Amount',

  // 预存款相关
  '预存款总额': ' Total Deposit',
  '预存款余额': 'Deposit Balance',
  '充值申请': 'Recharge Application',
  '退款申请': 'Refund Application',
  '申请类型': 'Request type',
  '充值': ' Top-up',
  '申请开始日期': 'Application Start Date',
  '申请截止日期': 'Application And Date',
  '查看附件': 'View Attachment',
  '附件': 'Attachment',
  '查看': 'View',
  '提交授信申请': 'Submit Credit Application',
  '授信详情预览': 'Credit Details Preview',
  '暂无附件可查看': 'No attachments to view',
  '已申请金额': 'Applied Amount',
  '支付凭证附件': 'Payment Voucher Attachment',
  '返回': 'Return',
  '取消申请': 'Cancel Application',
  '请确认取消申请内容': 'Please confirm cancellation of application content',
  '取消成功': 'Cancelled Successfully',
  '不能为空': 'Is required',
  '请确认申请内容': 'Please confirm application content',
  '申请成功': 'Applied successfully',
  '请完善基础信息': 'Please complete basic information',

  // 交易相关
  '交易开始日期': 'Transaction Start Date',
  '截止日期': 'End Date',
  '金额': 'Amount',
  '余额': 'Balance',
  '流水号': 'Transaction Serial',
  '交易时间': 'Transaction Time',
  '操作人': 'Operator',

  // 系统相关
  '用户昵称': 'User Nickname',
  '手机号码': 'Tel',
  '邮箱': 'E-Mail',
  '男': 'Male',
  '女': 'Female',
  '保存': 'Save',
  '关闭': 'Close',
  '用户昵称不能为空': 'User nickname is required',
  '邮箱地址不能为空': 'Email address is required',
  '请输入正确的邮箱地址': 'Please enter the correct email address',
  '手机号码不能为空': 'Mobile phone number is required',
  '请输入正确的手机号码': 'Please enter the correct mobile phone number',
  '修改成功': 'Modification Successful',
  '语言设置': 'Language Setting',
  '语言': 'Language',
  '切换语言': 'Switch Language',
  '点击上传头像': 'Click to Upload Avatar',
  '上传头像图片只能是jpg/png格式！': 'Avatar image can only be in jpg/png format!',
  '上传头像图片大小不能超过5MB！': 'Avatar image size cannot exceed 5MB!',
  '个人信息': 'Personal Info.',
  '创建日期': ' Date Created',
  '资料变更': ' Information Changing',
  '修改密码': 'Security',
  '旧密码': 'Old Password',
  '请输入旧密码': 'Please enter the old password',
  '新密码': 'New password',
  '请输入新密码': 'Please enter a new password',
  '确认密码': 'Confirm Password',
  '请确认新密码': 'Please confirm the new password',
  '旧密码不能为空': 'The old password is required',
  '长度在 8 到 16 个字符': 'Length between 8 and 16 characters',
  '确认密码不能为空': '8–16 characters required',

  // 字典相关
  '字典名称': 'Dictionary Name',
  '字典类型': 'Dictionary Type',
  '字典状态': 'Dictionary Status',
  '开始日期': 'Start Date',
  '结束日期': 'End Date',
  '新增': ' Add',
  '修改': 'Edit',
  '删除': 'Delete',
  '导出': 'Export',
  '刷新缓存': 'Refresh Cache',
  '字典编号': 'Dictionary No.',
  '备注': 'Remarks',
  '请输入字典类型': 'Please enter dictionary type',
  '请输入内容': 'Please enter content',
  '确定': 'Confirm',
  '字典名称不能为空': 'Dictionary name is required',
  '字典类型不能为空': 'Dictionary type is required',
  '添加字典类型': 'Add Dictionary Type',
  '修改字典类型': 'Modify Dictionary Type',
  '新增成功': 'Added successfully',
  '是否确认删除字典编号为': 'Are you sure to delete dictionary number',
  '的数据项?': 'Data item of?',
  '删除成功': ' Deleted successfully',
  '是否确认导出所有数据?': 'Confirm export of all data?',
  '刷新成功': 'Refreshed successfully',
  '字典标签': 'Dictionary Label',
  '数据状态': 'Data Status',
  '字典编码': 'Dictionary Code',
  '字典键值': 'Dictionary Key Value',
  '字典排序': 'Dictionary sort',

  // 组件相关
  '选择地区': 'Select Area',
  '地区(英文)': ' Region (English)',
  '地区(中文)': 'Region (Chinese)',
  '编码(2个字符)': 'Code (2 Characters)',
  '编码(3个字符)': 'Code (3 Characters)',
  '排序': 'Sort',
  '已选中': 'Selected',
  '选择': 'Select',
  '高度': 'Height',
  '自动高度': 'Auto Height',
  '固定高度': 'Fixed Height',
  '分页': 'Pagination',
  '每页条数': 'Items per Page',
  '行高': 'Row Height',
  '表头高度': 'Header Height',
  '表项高度': 'Item Height',
  '恢复默认': 'Restore Default',
  '刷新页面': 'Refresh the Page',

  // 支付相关组件
  '提交支付': 'Submit Payment',
  '选择支付方式': 'Select Payment Method',
  '预存款支付': 'Deposit Payment',
  '当前余额': 'Current Balance',
  '余额为0，请直接使用支付凭证支付': 'Balance is 0, please pay directly with payment voucher',
  '支付凭证支付': 'Payment Voucher Payment',
  '请上传支付凭证': 'Please upload payment voucher',
  '支持多种格式上传': 'Supports multiple format uploads',
  '支付节点选择': 'Payment Node Selection',
  '支付金额': 'Payment Amount',
  '预存款余额不足，需再补充支付凭证支付金额': 'Pre-deposit balance is insufficient, need to supplement with payment voucher amount',
  '补充支付凭证': 'Supplement Payment Voucher',
  '下一步': 'Next',
  '上一步': 'Previous',
  '请选择支付节点': 'Please select payment node',
  '请上传支付凭证': 'Please upload the payment voucher.',
  '提交成功': 'Submitted successfully',

  // 发票相关
  '申请开票': 'Apply for Invoice',
  '发票类型': 'Invoice Type',
  '发票类型不能为空': 'Invoice Type is required',
  '联系人电话': 'Contact Phone',
  '联系人电话不能为空': 'Contact Phone is required',
  '邮箱不能为空': 'Email is required',
  '公司名称不能为空': 'Company Name is required',
  '纳税人识别号': 'Tax ID',
  '识别号不能为空': 'Tax ID is required',
  '公司地址': 'Company Address',
  '公司电话': 'Company Phone',
  '银行账户': 'Bank Account',
  '提交申请': 'Submit Application',
  '发票申请': 'Invoice application',
  '已申请': 'Already Applied',

  // 价格相关
  '房间价格': 'Room Price',
  '单人包房价格': 'Single-Occupancy Price',
  '铺位类型': 'Berth Type',
  '铺位价格': 'Berth Price',

  // 其他
  '是否确认导出全部旅客船票?': 'Are you sure to export all passenger tickets?',
  '请输入合适的折扣率(80%~100%)': 'Please enter an appropriate discount rate (80%~100%)',
  '是否确认导出全部账单?': 'Are you sure to export all bills?',
  '确认导出乘客信息名单?': 'Confirm export of passenger information list?',
  '请选择航次': 'Please select voyage',
  '是否确认导出全部旅客船票?': 'Are you sure to export all passenger tickets?',
  '是否确认导出全部账单?': 'Are you sure to export all bills?',
  '确认导出乘客信息名单?': 'Confirm export of passenger information list?',

// 新增的遗漏翻译内容
  // 乘客信息相关
  '乘客基础信息': 'Guest Basic Information',
  '医疗信息': 'Medical Information Form',
  '到达/离开信息': 'Arrival/Departure Details',
  '旅客信息': 'Guest Information',
  '免费更换出行人剩余次数': 'Remaining Number of Free Guest Changes',
  '临近出行，修改乘客信息请联系后台工作人员': 'For modifications close to departure, please contact our support staff to change guest information.',
  '中国护照上传识别': 'Chinese Passport Upload & Recognition',
  '出行人信息解锁': 'Unlock Guest Information',
  '信息调整审核中，禁止解锁': 'Modification under review. Unlocking is prohibited.',
  '出行人信息锁定': 'Lock Guest Information',
  '中文姓': 'Surname (Chinese)',
  '中文名': 'Given Name (Chinese)',
  '英文姓': 'Surname (English)',
  '英文名': 'Given Name (English)',
  '出生日期': 'Date of Birth',
  '年龄类型(开航时)': 'Age Type (at Embarkation)',
  '首选名称/昵称(船上称呼)': 'Preferred Name/Nickname (Onboard Use)',
  '国籍': 'Nationality',
  '请选择': 'Please Select',
  '出生国': 'Country of Birth',
  '邮寄地址': 'Mailing Address',
  '手机号码': 'Mobile Number',
  '同住编号': 'Shared Booking ID',
  '床配置': 'Bed Configuration',
  '大床': 'Queen Bed',
  '双床': 'Twin Beds',
  '靴子': 'Boots',
  '自带': 'Bringing Own',
  '不自带': 'Not Bringing Own',
  '夹克衫': 'Jacket',
  '乘客序列号': 'Guest Serial Number',
  '出行证件': 'Travel Documents',
  '证件类型': 'Document Type',
  '证件号码': 'Document Number',
  '签发时间': 'Issue Date',
  '到期时间': 'Expiry Date',
  '签发地': 'Place of Issue',
  '证件类型2': 'Secondary Document Type',
  '证件号码2': 'Secondary Document Number',
  '签发时间2': 'Secondary Issue Date',
  '到期时间2': 'Secondary Expiry Date',
  '签发地2': 'Secondary Place of Issue',
  '保险信息': 'Insurance Information',
  '保险公司名称': 'Insurance Company',
  '保单号码': 'Policy Number',
  '保险电话': 'Insurance Emergency Contact',
  '紧急联系人': 'Emergency Contact',
  '联系人姓名': 'Contact\'s Name',
  '联系人电话': 'Contact\'s Phone',
  '联系人邮箱': 'Contact\'s Email',
  '与本人关系': 'Relationship to Guest',
  '费用摘要': 'Fee Summary',
  '更改费用': 'Change Fee',
  '合计更改费': 'Total Change Fee',
  '请在下面列出重大残疾': 'Please list any significant disabilities below',
  '例如失明、耳聋、肢体截肢、对拐杖或拐杖等助行器的依赖，轮椅依靠、瘫痪': 'e.g., blindness, deafness, limb amputation, reliance on walking aids (cane, crutches), wheelchair use, paralysis',
  '无': 'None',
  '请列出所有饮食限制、包括危及生命的食物过敏、以及简单的饮食偏好': 'Please list all dietary restrictions, including life-threatening food allergies, and simple dietary preferences',
  '例如素质者': 'e.g., Vegetarian',
  '请列出您所有敏感或过敏的药物/物质': 'Please list all medications/substances to which you are sensitive or allergic',
  '食物除外': 'Excluding Food',
  '请列出您目前或常规服用的所有药物': 'Please list all medications you are currently or regularly taking',
  '请列出上面没有提到的所有当前医疗状况': 'Please list any other current medical conditions not mentioned above',
  '抗凝血剂(血液稀释剂)咨询': 'Anticoagulant (Blood Thinner) Consultation',
  '您目前正在服用warfarin(Coumadin)或debigatran(Pradaxa)等血液稀释剂吗？': 'Are you currently taking blood thinners such as Warfarin (Coumadin) or Dabigatran (Pradaxa)?',
  '是': 'Yes',
  '否': 'No',
  '到达信息': 'Arrival Information',
  '您是否通过飞机抵达登船港口所在区域？': 'Are you arriving by air into the port city?',
  '航班日期': 'Flight Date',
  '请选择日期': 'Please Select Date',
  '航空公司': 'Airline',
  '航班号码': 'Flight Number',
  '起飞机场(三字符)': 'Departure Airport (3-letter Code)',
  '到达时间(当地时间)': 'Arrival Time (Local Time)',
  '请选择到达时间': 'Please Select Arrival Time',
  '到达机场(三字符)': 'Arrival Airport (3-letter Code)',
  '是否需要接驳服务(登船日)？': 'Require transfer service on embarkation day?',
  '接驳出发点(登船日)': 'Transfer Pick-up Point (Embarkation Day)',
  '接驳时间(登船日)': 'Transfer Time (Embarkation Day)',
  '离开信息': 'Departure Information',

  // 退订相关
  '退订订单情况': 'Cancellation Status',
  '已支付金额': 'Amount Paid',
  '退订规则名称': 'Cancellation Policy Name',
  '附加产品退订规则名称': 'Ancillary Service Cancellation Policy',
  '舱房退订手续费': 'Cabin Cancellation Penalty',
  '附加产品退订手续费': 'Ancillary Service Cancellation Penalty',
  '退订后订单总额': 'Order Total After Cancellation',
  '人员数': 'Number of Guests',
  '附加服务购买数': 'Number of Ancillary Services Purchased',
  '销售类型': 'Sales Type',
  '根据匹配规则，管理员后续或调为:': 'Per matching rules, administrator may later adjust to:',
  '佣金比率': 'Commission Rate',
  '支付节点规则': 'Payment Milestone Rules',
  '应退金额': 'Refundable Amount',
  '退订舱房': 'Cancel Cabin',
  '房间号': 'Cabin Number',
  '入住乘客': 'Assigned Guest(s)',
  '舱房总价': 'Total Cabin Fare',
  '佣金金额': 'Commission Amount',
  '手续费金额': 'Penalty Amount',
  '原应付金额': 'Original Amount Due',
  '预计退款': 'Estimated Refund',
  '退订附加产品': 'Cancel Ancillary Service',
  '产品代码': 'Product Code',
  '价格': 'Price',
  '购买乘客': 'Purchasing Guest',
  '退款记录': 'Refund Record',
  '退款类型': 'Refund Type',
  '支付凭证': 'Proof of Payment',
  '查看附件': 'View Attachment',
  '请确认申请退订内容': 'Please confirm the cancellation details',
  '退款订单情况': 'Refund Order Status',
  '确定取消退订申请吗?': 'Are you sure you want to cancel this cancellation request?',
  '确定取消更改申请吗?': 'Are you sure you want to cancel this modification request?',
  '乘客修改情况': 'Guest Modification Status',
  '查看订单详情': 'View Order Details',
  '乘客信息详情': 'Guest Information Details',
  '请确认申请退订金额': 'Please confirm the refund amount requested',
  '提交申请': 'Submit Application',

  // 切舱相关
  '切舱分配详情': 'Cabin Allocation Details',
  '按房间统计': 'By Cabin (Statistics)',
  '舱房等级编号': 'Cabin Category Code',
  '已切数量(间)': 'Cabins Allocated',
  '已售数量(间)': 'Cabins Sold',
  '剩余': 'Remaining',
  '按铺位统计': 'By Berth (Statistics)',
  '已切数量(铺位)': 'Berths Allocated',
  '已售数量(铺位)': 'Berths Sold',
  '合计舱房价格': 'Total Cabin Price',
  '关闭': 'Close',

  // 附加产品相关
  '清除': 'Clear',
  '批量导入': 'Bulk Import',
  '可预订附加产品查询': 'Available Ancillary Services Query',
  '乘客': 'Guest',
  '产品类型': 'Product Type',
  '产品名称': 'Product Name',
  '产品代码': 'Product Code',
  '单价': 'Unit Price',
  '同乘客追加': 'Add for Same Guest',
  '同产品追加': 'Add Same Product',
  '提交预订': 'Submit Booking',
  '将文件拖到此处，或': 'Drag file here, or',
  '点击上传': 'click to upload',
  '仅允许导入xls、xlsx格式文件。': 'Only xls and xlsx file formats are allowed.',
  '提交': 'Submit',
  '提示': 'Notification',
  'agency.group.import.template参数未配置': 'Parameter:agency.group.import.template is not configured',
  '正在下载文件，请稍候': 'Downloading file, please wait...',
  '旅客导入': 'Guest Import',
  '导入结果': 'Import Results',
  '请选择待清理记录': 'Please select records to cleanup',
  '确认删除选中的记录吗？': 'Confirm deletion of selected records?',
  '请选择乘客': 'Please select guest(s)',
  '请选择附加产品': 'Please select ancillary service(s)',
  '请完善填写': 'Please complete the information',
  '附加产品添加': 'Add Ancillary Service',
  '已成功': 'Successful',

  // 乘客更新相关
  '名单导入': 'Manifest Import',
  '空余舱房导出': 'Export Available Cabins',
  '乘客数': 'Guest Count',
  '存在异常': 'Anomalies Detected',
  '请修复异常后重新导入': 'Please correct the anomalies and re-import',
  '拿舱记录编号': 'Allocation Record ID',
  '房型等级编号': 'Cabin Grade Code',
  '房型等级名称': 'Cabin Grade Name',
  '录入铺位类型': 'Enter Berth Type',
  '是否包房': 'Whole Cabin Booking',
  '同住标识': 'Shared Booking Identifier',
  '姓': 'Last Name',
  '名': 'First Name',
  '出生国': 'Country of Birth',
  '国籍': 'Nationality',
  '昵称(船上称呼)': 'Nickname (Onboard)',
  '联系电话区号': 'Phone Area Code',
  '联系电话': 'Phone Number',
  '邮寄地址': 'Mailing Address',
  '电子邮箱': 'Email',
  '证件号码1': 'Document Number 1',
  '证件生效期1': 'Document Valid From 1',
  '证件有效期1': 'Document Valid To 1',
  '证件签发地1': 'Place of Issue 1',
  '保险编号': 'Policy Number',
  '保险联系电话': 'Insurance Contact Phone',
  '紧急联系人与其关系': 'Emergency Contact & Relationship',
  '紧急联系人姓名': 'Emergency Contact Name',
  '紧急联系人电话区号': 'Emergency Contact Area Code',
  '紧急联系人电话': 'Emergency Contact Phone',
  '紧急联系人邮箱': 'Emergency Contact Email',
  '是否与同伴共用大号床': 'Sharing Queen Bed with Companion',
  '分团号': 'Sub-Group Number',
  '证件号码2': 'Document Number 2',
  '证件生效期2': 'Document Valid From 2',
  '证件有效期2': 'Document Valid To 2',
  '证件签发地2': 'Place of Issue 2',
  '重大残疾情况': 'Significant Disability Information',
  '所有饮食限制': 'All Dietary Restrictions',
  '过敏信息': 'Allergy Information',
  '目前或常规服用的所有药物名称': 'Names of All Current or Regular Medications',
  '其他医疗状况': 'Other Medical Conditions',
  '正在服用warfarin（Coumadin）或dabigatran（Pradaxa）等血液稀释剂': 'Taking blood thinners (e.g., Warfarin/Coumadin, Dabigatran/Pradaxa)',
  '衣服尺寸': 'Clothing Size',
  '靴子尺码': 'Boot Size',
  '是否自带鞋子': 'Bringing Own Shoes',
  '是否飞机抵达区域': 'Arriving by Air',
  '到达航班日期': 'Arrival Flight Date',
  '到达航空公司': 'Arrival Airline',
  '到达航班号码': 'Arrival Flight Number',
  '起飞机场（到达）': 'Departure Airport (Arrival)',
  '目的地机场（到达）': 'Destination Airport (Arrival)',
  '到达时间（当地）': 'Arrival Time (Local)',
  '是否飞机离开区域': 'Departing by Air',
  '离开航班日期': 'Departure Flight Date',
  '离开航空公司': 'Departure Airline',
  '离开航班号码': 'Departure Flight Number',
  '起飞机场（离开）': 'Departure Airport (Departure)',
  '起飞时间（当地）': 'Departure Time (Local)',
  '抵达时预订额外酒店房间': 'Booked Extra Hotel Room Upon Arrival',
  '是否需要接驳服务(登船日)': 'Require transfer service on embarkation day?',
  '接驳出发点(登船日)': 'Transfer Pick-up Point (Embarkation Day)',
  '接驳时间选择(登船日)': 'Transfer Time Selection (Embarkation Day)',
  '是否需要接驳服务(离船日)': 'Require transfer service on disembarkation day?',
  '接驳到达点(离船日)': 'Transfer Drop-off Point (Disembarkation Day)',
  '接驳时间选择(离船日)': 'Transfer Time Selection (Disembarkation Day)',
  '校验结果': 'Validation Result',
  '校验成功': 'Validation Successful',
  '存在信息异常.请修正错误': 'Data anomalies found. Please correct the errors.',
  '重置': 'Reset',
  '下载错误文件': 'Download Error File',
  '保存乘客信息': 'Save Guest Information',
  '提交预订乘客': 'Submit Booked Guests',
  '编号不能为空': 'ID cannot be empty',

  // 舱房相关
  '拿舱记录': 'Cabin Allocation Record',
  '拿舱类型': 'Allocation Type',
  '铺位': 'Berth',
  '整单退': 'Full Order Refund',
  '无损退订': 'Penalty-Free Cancellation',
  '实际舱房费用': 'Actual Cabin Cost',
  '已入住': 'Occupied',
  '更改费用': 'Change Fee',
  '总价格': 'Total Price',
  '房间最大入住人数': 'Maximum Cabin Occupancy',
  '已入住人数': 'Number of Guests',
  '设置包房': 'Set as Whole Cabin',
  '取消包房': 'Revert Whole Cabin',
  '移除乘客': 'Remove Guest',
  '选择包房乘客': 'Select Guests for Whole Cabin',
  '正在生成预览': 'Generating Preview',
  '请选择包房乘客': 'Please select guests for the whole cabin',
  '包房设置成功': 'Whole Cabin Set Successfully',
  '是否取消包房?': 'Cancel whole cabin booking?',
  '是否移除乘客?': 'Remove guest?',

  // 附加产品相关
  '旅客姓名': 'Guest Name',
  '旅客主证件': 'Primary Travel Document',
  '附加产品类型': 'Ancillary Service Type',
  '附加产品': 'Ancillary Service',
  '添加预订': 'Add Booking',
  '批量退订': 'Bulk Cancellation',
  '预定号': 'Booking Number',
  '姓名': 'Name',
  '主证件号': 'Primary Document Number',
  '附加服务退订申请': 'Ancillary Service Cancellation Request',
  '添加附加产品预订': 'Add Ancillary Service Booking',
  '确定取消预订吗？': 'Confirm booking cancellation?',
  '附加产品取消': 'Ancillary Service Cancellation',

  // 舱房信息相关
  '航程信息': 'Voyage Information',
  '当前航次为': 'Current Voyage:',
  '开航时间': 'Sailing Date/Time',
  '结航时间': 'Return Date/Time',
  '当前销售规则': 'Current Sales Rules',
  '已切总数': 'Total Allocated',
  '间': 'Cabin(s)',
  'FOC规则': 'FOC Rule',
  '船票退订规则': 'Ticket Cancellation Policy',
  '附加产品退订规则': 'Ancillary Service Cancellation Policy',
  '支付节点规则': 'Payment Milestone Rules',
  '舱房价格': 'Cabin Price',
  '切舱申请记录': 'Cabin Allocation Request Record',
  '切舱时间': 'Allocation Time',
  '支付期限': 'Payment Deadline',
  '拿舱总数': 'Total Cabins Allocated',
  '铺位总数': 'Total Berths Allocated',
  '支付节点列表': 'Payment Milestone List',
  '付款节点': 'Payment Milestone',
  '付款比例': 'Payment Percentage',
  '比例': 'Percentage',
  '尾款': 'Final Payment',
  '付款截止时间': 'Payment Due Date',
  '支付时间': 'Payment Time',
  '价格详情': 'Price Details',
  '切舱记录详情': 'Allocation Record Details',

  // 业务信息相关
  '支付/审核通过时间': 'Payment/Approval Time',
  '支付流水号': 'Payment Reference Number',
  '支付方式': 'Payment Method',
  '支付凭证': 'Proof of Payment',
  '支付状态': 'Payment Status',

  // 其他遗漏内容
  '减': 'Deduct',
  '不再适用规则,退订后将追加原免除金额': 'Rule no longer applicable. Original waived amount will be added back upon cancellation.',
  'FOC规则': 'FOC Rule',
  '新增行': 'Add Row',
  '名单导出': 'Export Manifest',
  '导出旅客对账单': 'Export Guest Statement',
  '推送补全信息': 'Push for Information Completion',
  '退订': 'Cancel',

  '保存失败，缺少必填项！': 'Save failed. Required fields are missing!',
  '规则代码': 'Rule Code',
  '规则名称': 'Rule Name',
  '生效时间': 'Effective Time',
  '开始时间': 'Start Time',
  '结束时间': 'End Time',
  '描述': 'Description',
  '配置模块': 'Configuration Module',
  '说明：出发日前几天(含当日),符合规则房数的订单取消时按房费的百分比扣减手续费。': 'Note: For cancellations made [X] days prior to departure (including departure day), a penalty calculated as a percentage of the cabin fare will be charged for orders meeting the rule\'s room criteria.',
  '请按照距离开航日期从远到近的日期进行相关配置，否则可能影响官网内容显示': 'Please configure settings in chronological order from farthest to nearest to the sailing date, otherwise it may affect the display on the official website.',
  '如:': 'e.g.,',
  '出发日期': 'Departure Date',
  '日期类型': 'Date Type',
  '天数范围': 'Day Range',
  '手续费方式': 'Penalty Type',
  '请选择邮轮': 'Please Select Cruise',
  '请选择销售类型': 'Please Select Sales Type',
  '请输入规则代码': 'Please Enter Rule Code',
  '请输入规则名称': 'Please Enter Rule Name',
  '请输入描述': 'Please Enter Description',
  '日期类型不能为空': 'Date Type is required',
  '请选择日期类型': 'Please Select Date Type',
  '起始天数不能为空': 'Start Day is required',
  '起始': 'Start',
  '结束天数不能为空': 'End Day is required',
  '结束': 'End',
  '手续费方式不能为空': 'Penalty Type is required',
  '请选择手续费方式': 'Please Select Penalty Type',
  '百分比': 'Percentage',
  '固定金额': 'Fixed Amount',
  '按每房间固定金额': 'Fixed Amount Per Cabin',
  '手续费不能为空': 'Penalty Fee is required',
  '请输入百分比': 'Please Enter Percentage',
  '请输入金额': 'Please Enter Amount',
  '邮轮不能为空': 'Cruise is required',
  '销售类型不能为空': 'Sales Type is required',
  '规则代码不能为空': 'Rule Code is required',
  '规则名称不能为空': 'Rule Name is required',
  '结束天数必须大于起始天数': 'End Day must be greater than Start Day',
  '至少需保留一条模块记录': 'At least one module record must be retained',
  '保存成功': 'Save Successful',

  '是否跳过旅客确认': 'Skip Guest Confirmation?',
  '退订提示': 'Cancellation Notice',


  //kol相关
  '蚂蚁国际': 'Ant International',
  '在线支付': 'Online Payment',
  '已禁用': 'Disabled',
  '请输入有效支付金额': 'Please enter a valid payment amount',
  '支付金额不能大于原始金额': 'Payment amount cannot exceed the original amount',
  '存在还没支付完成的在线，前往支付？': 'There is an unfinished online payment. Proceed to pay?',
  '是否取消当前在线支付？': 'Cancel the current online payment?',
  '禁止凭证支付': 'Voucher payment is prohibited',
  '暂无': 'None',
  '最小金额': 'Minimum Amount',
  '最大金额': 'Maximum Amount',
  '请输入支付金额': 'Please enter the payment amount',
  '信用卡': 'Credit Card',
  '钱包支付': 'E-Wallet Payment',

  // 从 settings.js 和 router/index.js 提取的缺失翻译
  '工作台': 'Workbench',
  '代理商信息': 'Agent Information',
  '散客预订': 'FIT Booking',
  '散客预订详情': 'FIT Booking Details',
  '散客票务中心': 'FIT Ticketing Center',
  '散客订单详情': 'FIT Order Details',
  '团体切舱申请': 'Group Cabin Allocation Application',
  '团体切舱': 'Group Cabin Allocation',
  '团体票务中心': 'Group Ticketing Center',
  '旅客信息管理': 'Passenger Information Management',
  '旅客信息列表': 'Passenger Information List',
  '订单退改申请记录': 'Order Refund & Modification Application Records',
  '船票退订': 'Cruise Ticket Cancellation',
  '船票退订详情': 'Cruise Ticket Cancellation Details',
  '附加服务退订': 'Add-Ons Cancellation',
  '附加服务退订详情': 'Add-Ons Cancellation Details',
  '退款申请': 'Refund Application',
  '乘客信息修改': 'Passenger Information Modification',
  '乘客信息变更': 'Passenger Information Change',
  '授信额度管理': 'Credit Line Management',
  '授信资金明细': 'Credit Fund Details',
  '资金明细': 'Fund Details',
  '账单列表': 'Bill List',
  '账单详情': 'Bill Details',

  // 从 addition.txt 补充的翻译
  '男': 'Male',
  '女': 'Female',
  '未知': 'Unknown',
  '显示': 'Show',
  '隐藏': 'Hide',
  '正常': 'Normal',
  '停用': 'Deactivated',
  '暂停': 'Suspended',
  '默认': 'Default',
  '系统': 'System',
  '是': 'Yes',
  '否': 'No',
  '通知': 'Notification',
  '公告': 'Announcement',
  '关闭': 'Close',
  '其他': 'Others',
  '新增': 'Add',
  '修改': 'Modify',
  '删除': 'Delete',
  '授权': 'Authorize',
  '导出': 'Export',
  '导入': 'Import',
  '强退': 'Force Logout',
  '生成代码': 'Generate Code',
  '清空数据': 'Clear Data',
  '成功': 'Success',
  '失败': 'Failure',
  '未值船': 'Not Checked In',
  '已值船': 'Checked In',
  '在船': 'On Board',
  '在岸': 'On Shore',
  '身份证': 'ID Card',
  '护照': 'Passport',
  '人工': 'Manual',
  '小程序': 'Mini Program',
  '自助机': 'Self-Service Kiosk',
  '登船': 'Embarkation',
  '离船': 'Disembarkation',
  '国内': 'Domestic',
  '国际': 'International',
  '发布': 'Publish',
  '草稿': 'Draft',
  '回收站': 'Recycle Bin',
  '文章': 'Article',
  '票务': 'Ticketing',
  '邮轮介绍': 'Cruise Introduction',
  '链接': 'Link',
  '未检票': 'Not Ticket Checked',
  '已检票': 'Ticket Checked',
  '已出闸': 'Exited Gate',
  '原创': 'Original',
  '转载': 'Reposted',
  '全电普通发票': 'E-Invoice(Ordinary)',
  '全电专用发票': 'E-Invoice(Special VAT)',
  '固定金额折扣': 'Fixed Amount Discount',
  '百分比折扣': 'Percentage Discount',
  '本地': 'Local',
  '阿里云': 'Alibaba Cloud',
  '临时': 'Temporary',
  '长期': 'Long-Term',
  '待审核': 'Pending Review',
  '已开通': 'Activated',
  '删除': 'Delete',
  '驳回': 'Rejected',
  '待审批': 'Pending Approval',
  '已通过': 'Approved',
  '未提交': 'Not Submitted',
  '已提交': 'Submitted',
  '被驳回': 'Rejected',
  '航线描述': 'Route Description',
  '热门标签': 'Popular Tags',
  '一级代理商': 'Tier 1 Agent',
  '二级代理商': 'Tier 2 Agent',
  '微信小程序': 'WeChat Mini Program',
  '团队代理': 'Group Agent',
  '散客代理': 'FIT Agent',
  '新建': 'Create',
  '待业务经理确认': 'Pending Business Manager Confirmation',
  '业务经理退回': 'Returned by Business Manager',
  '待付款完成': 'Pending Payment Completion',
  '财务退回': 'Returned by Finance',
  '付款完成': 'Payment Completed',
  '已生成结算单': 'Settlement Statement Generated',
  '待客户确认': 'Pending Customer Confirmation',
  '客户退回': 'Returned by Customer',
  '待付款': 'Pending Payment',
  '作废': 'Void',
  '额度申请': 'Credit Line Application',
  '下单': 'Place Order',
  '改签退差价': 'Refund of Price Difference for Ticket Modification',
  '改签补款': 'Supplemental Payment for Ticket Modification',
  '退票': 'Ticket Refund',
  '产品补购': 'Ancillary Product Repurchase',
  '额度退款': 'Credit Line Refund',
  '完成': 'Complete',
  '待退款完成': 'Pending Refund Completion',
  '始发港': 'Port of Departure',
  '途径港': 'Port of Call',
  '目的港': 'Port of Destination',
  '往返': 'Round Trip',
  '单程': 'One Way',
  '旅客': 'Passenger',
  '领队': 'Tour Leader',
  '已同意': 'Agreed',
  '申请退订中': 'Cancellation Application in Progress',
  '退订通过': 'Cancellation Approved',
  '退订驳回': 'Cancellation Rejected',
  '全额 (百分比)': 'Full Amount (Percentage)',
  '固定金额 (数额)': 'Fixed Amount (Figure)',
  '不允退票': 'No Refund Allowed',
  '回乡证': 'Home Return Permit',
  '台胞证': 'Taiwan Compatriot Permit',
  '待经理确认': 'Pending Manager Confirmation',
  '待财务确认': 'Pending Finance Confirmation',
  '待发起退款': 'Pending Refund Initiation',
  '旅客确认中': 'Pending Passenger Confirmation',
  '退订成功': 'Cancellation Successful',
  '旅客取消': 'Cancelled by Passenger',
  '直销': 'Direct Sales',
  '分销': 'Distribution',
  '散客代理': 'FIT',
  '用户组': 'User Group',
  '非用户组': 'Non-User Group',
  '取消退票': 'Cancel Ticket Refund',
  '待旅客确认': 'Pending Passenger Confirmation',
  '旅客待支付差价': 'Passenger Pending Payment of Price Difference',
  '改签成功': 'Ticket Modification Successful',
  '取消改签': 'Cancel Ticket Modification',
  '旅客超时取消': 'Cancelled by Passenger Due to Timeout',
  '超时取消': 'Cancelled Due to Timeout',
  '短信平台': 'SMS Platform',
  'SMTP': 'SMTP (Simple Mail Transfer Protocol)',
  '已开具': 'Issued',
  '增值税专用发票': 'Special VAT Invoice',
  '普通发票': 'Ordinary Invoice',
  '港澳通行证': 'Hong Kong & Macau Pass',
  '台湾通行证': 'Taiwan Travel Permit',
  '现金': 'Cash',
  '支付宝': 'Alipay',
  '银联卡': 'UnionPay Card',
  '积分': 'Points',
  '微信': 'WeChat',
  '预存款': 'Prepaid Deposit',
  '优惠券': 'Coupon',
  '订单确认': 'Order Confirmation',
  '订单取消': 'Order Cancellation',
  '值船提醒': 'Boarding Check-In Reminder',
  '合同签字通知': 'Contract Signing Notification',
  '充足': 'Sufficient',
  '少量': 'Limited',
  '待付定金': 'Pending Deposit Payment',
  '待补全款': 'Pending Full Payment Supplement',
  '完成支付': 'Complete Payment',
  '已退订': 'Cancelled',
  '已退款': 'Refunded',
  '已取消': 'Voided',
  '待付尾款': 'Pending Balance Payment',
  '支付完成': 'Payment Completed',
  '专业发票': 'Professional Invoice',
  '承运人 / 船名': 'Carrier/Vessel Name',
  '启航日期': 'Sailing Date',
  '航线行程': 'Route Itinerary',
  '预订编号': 'Booking Reference Number',
  '船舱楼层': 'Cabin Deck',
  '船舱位置': 'Cabin Location',
  '舱房类型': 'Cabin Type',
  '房间号码': 'Cabin Number',
  '船票类型 (个人)': 'Cruise Ticket Type (FIT)',
  '船票类型 (团队)': 'Cruise Ticket Type (Group)',
  '姓名': 'Name',
  '国家 / 地区': 'Country/Region',
  '旅客证件号': 'Passenger ID Number',
  '身份证号': 'ID Card Number',
  '联系方式': 'Contact Information',
  '免费': 'Free',
  '收费': 'Paid',
  'Web - 直销渠道 ': 'Web-Direct Sales Channel',
  'Agency - 代理渠道 ': 'Agency-Distribution Channel',
  'Partner - 第三方渠道 ': 'Partner-Third-Party Channel',
  'Interal - 内部渠道 ': 'Internal-Internal Channel',
  '售罄': 'Sold Out',
  '申请中': 'In Application',
  '充值预存款': 'Prepaid Deposit Recharge',
  '船票消费': 'Cruise Ticket Consumption',
  '附加费用支出': 'Additional Fee Expenditure',
  '年度奖励': 'Annual Incentive',
  '旅行社': 'Travel Agency',
  '公司': 'Company',
  '个人': 'Individual',
  '银行转账': 'Bank Transfer',
  '婴儿': 'Infant',
  '儿童': 'Child',
  '青年': 'Youth',
  '成年': 'Adult',
  '中老年': 'Middle-Aged and Elderly',
  '老年': 'Elderly',
  '系统默认': 'System Default',
  '创建': 'Create',
  '待切舱': 'Pending Cabin Allocation',
  '已切舱': 'Cabin Allocated',
  '未开票': 'Invoice Not Issued',
  '通用旅客类型': 'General Passenger Type',
  '未排房': 'Cabin Not Assigned',
  '已排房': 'Cabin Assigned',
  '代理商': 'Agent',
  '散客': 'FIT',
  '团队': 'Group',
  '待确认': 'Pending Confirmation',
  '直销': 'Direct Sales',
  '退款中': 'Refund in Progress',
  '退款成功': 'Refund Successful',
  '退款失败': 'Refund Failed',
  '阿里API错误': 'Alibaba API Error',
  '在线支付': 'Online Payment',
  '航次管理': 'Voyage Management',
  '批量排房': 'Bulk Cabin Assignment',
  '平台': 'CRS Platform',
  '邮轮通': 'Cruise App',
  'kol': 'KOL',
  '会员': 'Member',
  '船东': 'Ship Owner',
  '待退款': 'Pending Refund',
  '阿里API错误': 'Alibaba API Error',
  '否': 'No',
  '是': 'Yes',

  // 基础信息相关
  '基础信息': 'Basic Information',
  '代理商编号': 'Agent Code',
  '代理商名称': 'Agent Name',
  '等级': 'Level',
  '档案类型': 'File Type',
  '散客佣金比例': 'FIT Commission Rate',
  '团队佣金比例': 'Group Commission Rate',
  '办公电话': 'Office Phone',
  '企业邮箱': 'Corporate Email',
  '办公地址': 'Office Address',

  // 联系人信息相关
  '联系人信息': 'Contact Person Information',
  '联系人': 'Contact Person',
  '联系人电话': 'Contact Person Phone',
  '电子邮箱': 'Email Address',

  // 开票信息相关
  '开票信息': 'Invoicing Information',
  '公司名称': 'Company Name',
  '税号': 'Tax ID',
  '单位地址': 'Company Address',
  '电话号码': 'Phone Number',
  '开户银行': 'Bank of Account',
  '银行账户': 'Bank Account Number',

  // 合同信息相关
  '合同信息': 'Contract Information',
  '合同名称': 'Contract Name',
  '开始日期': 'Start Date',
  '结束日期': 'End Date',
  '签署人': 'Signatory',
  '已失效': 'Invalidated',
  '未生效': 'Not Effective',
  '生效中': 'Active',
  '已过期': 'Expired',
  '附件': 'Attachment',

  // 注册相关
  '邮轮渠道票务平台': 'Cruise Channel Ticketing Platform',
  '账号': 'Account',
  '密码': 'Password',
  '确认密码': 'Confirm Password',
  '注册': 'Register',
  '注册中': 'Registering',
  '使用已有账户登录': 'Log in with Existing Account',
  '两次输入的密码不一致': 'The two passwords entered do not match',
  '请输入您的账号': 'Please enter your account',
  '请输入您的密码': 'Please enter your password',
  '请再次输入您的密码': 'Please re-enter your password',
  '用户账号长度必须介于 2 和 20 之间': 'User account length must be between 2 and 20 characters',
  '用户密码长度必须介于 5 和 20 之间': 'User password length must be between 5 and 20 characters',
  '请输入验证码': 'Please enter the verification code',
  '恭喜你': 'Congratulations',
  '您的账号': 'Your Account',
  '注册成功': 'Registration Successful',
  '系统提示': 'System Notification',

  // 登录相关
  '系统登录': 'System Login',
  '用户名': 'Username',
  '请输入密码': 'Please enter your password',
  '验证码': 'Verification Code',
  '拖动滑块': 'Drag the Slider',
  '文字点选': 'Text Selection',
  '短信验证码': 'SMS Verification Code',
  '获取验证码': 'Get Verification Code',
  '后重新获取': 'Retry after',
  '记住密码': 'Remember Password',
  '登录': 'Login',
  '登录中': 'Logging in',
  'NFC登录': 'NFC Login',
  '更改语言': 'Change Language',
  '中文': 'Chinese',
  '提示': 'Prompt',
  '请输入用户名': 'Please enter your username',
  '重置密码': 'Reset Password',
  '安全风险（强制措施）': 'Security Risk (Mandatory Measure)',
  '已超出': 'Exceeded',
  '天未修改密码，修改后可正常登录': 'days without password modification. You can log in normally after changing the password',
  '新密码': 'New Password',
  '再输一次': 'Re-enter',
  '密码长度至少 8 位，且不超过 16 位': 'Password length must be at least 8 characters and no more than 16 characters',
  '满足至少三种组合': 'Meet at least three combinations',
  '大写字母：A, B, C…Z': 'Uppercase Letters: A, B, C…Z',
  '小写字母：a, b, c…z': 'Lowercase Letters: a, b, c…z',
  '数字：0, 1, 2…9': 'Numbers: 0, 1, 2…9',
  '特殊符号：~, !, @, #, ,, %, ^':'special：~, !, @, #, ,, %, ^',
  '确认': 'Confirm',
  '请填写登录信息': 'Please fill in the login information',
  '请填写密码信息': 'Please fill in the password information',
  '密码不一致，请重新输入': 'Passwords do not match. Please re-enter',
  '用户密码长度必须介于 8 和 16 之间，且需满足至少三种组合': 'User password length must be between 8 and 16 characters and meet at least three combinations',
  '不能包含连续 3 个相同或者连续的字符或数字': 'Cannot contain 3 consecutive identical or sequential characters or numbers',
  '重置成功，请重新登录！': 'Reset successful. Please log in again!',
  'Please read your employee card through the NFC': 'Please read your employee card through the NFC',

  // 仪表板相关
  '航次预订情况': 'Cruise Voyage Booking Status',
  '预订情况': 'Booking Status',
  '搜索': 'Search',
  '间': 'Room (s)',
  '航次': 'Voyage',
  '日期': 'Date',
  '预订进度': 'Booking Progress',
  '人数': 'Person (s)',
  '金额': 'Amount',
  '待处理事项': 'Pending Tasks',
  '逾期订单提醒': 'Overdue Order Reminder',
  '订单号': 'Order Number',
  '逾期 (天)': 'Overdue (Days)',
  '支付节点': 'Payment Node',
  '处理': 'Process',
  '付款提醒 (未来一个月)': 'Payment Reminder (Next Month)',
  '剩余 (天)': 'Remaining (Days)',
  '到期时间': 'Due Time',
  '查看详情': 'View Details',
  '佣金收益': 'Commission Income',
  '年': 'Year',
  '季': 'Quarter',
  '月': 'Month',
  '累计佣金': 'Cumulative Commission',
  '分航次佣金统计': 'Commission Statistics by Voyage',
  '佣金': 'Commission',

  // 工作区相关
  '基础信息测试': 'Basic Information Test',
  '联系人': 'Contact Person',
  '联系人电话': 'Contact Person Phone',
  '合同开始时间': 'Contract Start Time',
  '合同结束时间': 'Contract End Time',
  '授信额度 (元)': 'Credit Line',
  '地址': 'Address',

  '搜索':'Search',
  '预订人' : 'Booker',

  //  todo 待核对翻译

  '下单开始日期' : 'Date Start',
  '下单结束日期' : 'Date End',
  '邮轮名称' : 'Cruise Ship Name',
  '切舱状态' : 'Allocation Status',
  '航线' : 'Route',
  '开航日期' : 'Sailing Date',
  '行程天数' : 'Duration (Days)',
  '促销方案' : 'Promotion',
  '房间库存' : 'Room Inventory',
  '铺位库存' : 'Berth Inventory',
  '申请切舱' : 'Request Allocation',

  '已拒绝': 'Rejected',

  // Added from zh-cn/addition.txt
  '折叠菜单': 'Collapse Menu',
  '全屏': 'Full Screen',
  '团体订单详情': 'Group Order Details',
  'KOL散客': 'KOL FIT',
  '减少费用项': 'Deduction Items',
  '合计信息': 'Summary Information',
  '按房间总数': 'By Total Rooms',
  '按铺位总数': 'By Total Berths',
  '总人数': 'Total Guests',
  '原舱房金额': 'Original Cabin Amount',
  '免费仓房费用': 'FOC Cabin Fee',
  '应结算舱房总额': 'Total Cabin Amount Payable',
  '附加费用项': 'Additional Fee Items',
  '增加费用项总额': 'Total Added Fees',
  '减少费用项总额': 'Total Deducted Fees',
  '应结算总金额': 'Total Amount Payable',

  '预存款充值': 'Deposit Top-up',
  '预存款退款': 'Deposit Refund',
  '申请金额': 'Application Amount',

  '已完成': 'Completed',
  '舱房数': 'Number of Cabins',

  '您是否在离船后立即乘坐飞机离开港口所在区域？': 'Will you depart the port city by air immediately after disembarkation?',
  '起飞时间': 'Departure Time',
  '请选择起飞时间': 'Please select departure time',
  '是否需要接驳服务(离船日)？': 'Require transfer service on disembarkation day?',
  '接驳出发点(离船日)': 'Transfer Pick-up Point (Disembarkation Day)',
  '接驳时间(离船日)': 'Transfer Time (Disembarkation Day)',
  '额外住宿': 'Extra Accommodation',
  '我们将在船票覆盖的团体住宿之前抵达港口所在区域，并在以下酒店预订了额外的房间？': 'We will arrive before the group accommodation covered by the ticket and have booked extra hotel room(s) as below.',

  '系统提示': 'System Prompt',
  '取消': 'Cancel',
  '确定': 'Confirm',

  '即将售罄': 'Almost Sold Out',

  '邮轮渠道票务平台': 'Cruise Channel Ticketing Platform',
  '个人中心': 'Personal Center',
  '收件箱': 'Inbox',
  '规则设置': 'Rule Settings',
  '虚拟组件': 'Virtual Component',
  '版本': 'Version',

  '1月': 'Jan',
  '2月': 'Feb',
  '3月': 'Mar',
  '4月': 'Apr',
  '5月': 'May',
  '6月': 'Jun',
  '7月': 'Jul',
  '8月': 'Aug',
  '9月': 'Sep',
  '10月': 'Oct',
  '11月': 'Nov',
  '12月': 'Dec',

  //  todo 待核对翻译 (from zh-cn/addition.txt, deduped common existing keys)
  '系统账户管理': 'System Account Management',
  '系统监控': 'System Monitoring',
  '系统工具': 'System Tools',
  '泛网科技': 'Fanwang Tech',
  '用户管理': 'User Management',
  '角色管理': 'Role Management',
  '菜单管理': 'Menu Management',
  '部门管理': 'Department Management',
  '岗位管理': 'Position Management',
  '字典管理': 'Dictionary Management',
  '参数设置': 'Parameter Settings',
  '通知公告': 'Notices & Announcements',
  '日志管理': 'Log Management',
  '在线用户': 'Online Users',
  '定时任务': 'Scheduled Tasks',
  '表单构建': 'Form Builder',
  '代码生成': 'Code Generator',
  '操作日志': 'Operation Logs',
  '登录日志': 'Login Logs',
  '用户查询': 'User Query',
  '用户新增': 'Add User',
  '用户修改': 'Edit User',
  '用户删除': 'Delete User',
  '用户导出': 'Export Users',
  '用户导入': 'Import Users',
  '角色查询': 'Role Query',
  '角色新增': 'Add Role',
  '角色修改': 'Edit Role',
  '角色删除': 'Delete Role',
  '角色导出': 'Export Roles',
  '菜单查询': 'Menu Query',
  '菜单新增': 'Add Menu',
  '菜单修改': 'Edit Menu',
  '菜单删除': 'Delete Menu',
  '部门查询': 'Department Query',
  '部门新增': 'Add Department',
  '部门修改': 'Edit Department',
  '部门删除': 'Delete Department',
  '岗位查询': 'Position Query',
  '岗位新增': 'Add Position',
  '岗位修改': 'Edit Position',
  '岗位删除': 'Delete Position',
  '岗位导出': 'Export Positions',
  '字典查询': 'Dictionary Query',
  '字典新增': 'Add Dictionary',
  '字典修改': 'Edit Dictionary',
  '字典删除': 'Delete Dictionary',
  '字典导出': 'Export Dictionaries',
  '参数查询': 'Parameter Query',
  '参数新增': 'Add Parameter',
  '参数修改': 'Edit Parameter',
  '参数删除': 'Delete Parameter',
  '参数导出': 'Export Parameters',
  '公告查询': 'Announcement Query',
  '公告新增': 'Add Announcement',
  '公告修改': 'Edit Announcement',
  '公告删除': 'Delete Announcement',
  '操作查询': 'Operation Query',
  '操作删除': 'Delete Operation',
  '登录查询': 'Login Query',
  '登录删除': 'Delete Login',
  '账户解锁': 'Unlock Account',
  '在线查询': 'Online Query',
  '批量强退': 'Force Logout (Batch)',
  '单条强退': 'Force Logout (Single)',
  '任务查询': 'Job Query',
  '任务新增': 'Add Job',
  '任务修改': 'Edit Job',
  '任务删除': 'Delete Job',
  '状态修改': 'Status Change',
  '任务导出': 'Export Jobs',
  '生成查询': 'Generation Query',
  '生成修改': 'Edit Generation',
  '生成删除': 'Delete Generation',
  '导入代码': 'Import Code',
  '预览代码': 'Preview Code',
  '中央预订系统': 'Central Reservation System',
  '基础数据': 'Master Data',
  '邮轮信息': 'Cruise Info',
  '国家及地区': 'Countries & Regions',
  '港口': 'Ports',
  '位置': 'Location',
  '邮轮': 'Cruise Ship',
  '设施': 'Facilities',
  '楼层': 'Decks',
  '紧急集合区': 'Muster Station',
  '船舱类型': 'Cabin Category',
  '舱房等级': 'Cabin Grade',
  '省份': 'Province',
  '城市': 'City',
  '年龄': 'Age',
  '证件': 'Document',
  '航季': 'Sailing Season',
  '销售区域': 'Sales Region',
  '渠道分类': 'Channel Category',
  '资料分类': 'Document Category',
  '资料管理': 'Document Management',
  '说明维护': 'Description Maintenance',
  '船舱信息': 'Cabin Information',
  '规则管理': 'Rule Management',
  '代理商规则': 'Agent Rules',
  '代理类型配置': 'Agent Type Configuration',
  '年度奖励规则': 'Annual Incentive Rules',
  '佣金规则': 'Commission Rules',
  '付款提醒': 'Payment Reminder',
  '发送通知规则': 'Notification Rules',
  '注意事项配置': 'Notes Configuration',
  '支付方式': 'Payment Methods',
  '发票模板': 'Invoice Template',
  '预订配置': 'Booking Configuration',
  '支付节点规则': 'Payment Milestone Rules',
  '船票退订规则': 'Ticket Cancellation Rules',
  '附加产品退订规则': 'Ancillary Service Cancellation Rules',
  '促销规则': 'Promotion Rules',
  '销售类型配置': 'Sales Type Configuration',
  '信息修改规则': 'Information Change Rules',
  '渠道票务端配置': 'Channel Ticketing Configuration',
  '年龄模板': 'Age Template',
  '附加费用项配置': 'Additional Fee Item Configuration',
  '登船凭证规则配置': 'Boarding Voucher Rules Configuration',
  '出行证件': 'Travel Documents',
  '航线管理': 'Route Management',
  '航线设置': 'Route Settings',
  '附加产品': 'Ancillary Products',
  '产品类型': 'Product Type',
  '产品设置': 'Product Settings',
  '价格管理': 'Pricing Management',
  '价格模板': 'Pricing Template',
  '基础价格新增': 'Add Base Price',
  '基础价格编辑': 'Edit Base Price',
  '基础价格删除': 'Delete Base Price',
  '优惠价格新增': 'Add Discount Price',
  '优惠价格编辑': 'Edit Discount Price',
  '优惠价格删除': 'Delete Discount Price',
  '渠道管理': 'Channel Management',
  '渠道设置': 'Channel Settings',
  '邮轮航次': 'Voyages',
  '邮轮管理': 'Cruise Management',
  '航次管理': 'Voyage Management',
  '邮轮通管理后台': 'Cruise App Admin',
  '前端内容管理': 'Frontend Content Management',
  '紧急推送': 'Emergency Push',
  '前端管理': 'Frontend Management',
  '邮轮通': 'Cruise App',
  '自助机': 'Kiosk',
  '娱乐信息': 'Entertainment Info',
  '公告': 'Announcement',
  '新增(基础信息)': 'Add (Basic Info)',
  '编辑(基础信息)': 'Edit (Basic Info)',
  '列表': 'List',
  '基础介绍': 'Basic Introduction',
  '帮助须知': 'Help & Notes',
  '自定义栏目': 'Custom Sections',
  '提示引用': 'Tip Reference',
  '功能条款': 'Terms of Use',
  '邮轮百科': 'Cruise Encyclopedia',
  '资源库': 'Media Library',
  'LOGO': 'LOGO',
  '图片': 'Images',
  '视频': 'Videos',
  '标签管理': 'Tag Management',
  '公开标签': 'Public Tags',
  '内部标签': 'Internal Tags',
  '事件管理': 'Event Management',
  '反馈记录': 'Feedback Records',
  '反馈类型': 'Feedback Types',
  '问卷调查': 'Survey',
  '配置': 'Configuration',
  '功能与栏目': 'Features & Sections',
  '装修': 'Theming',
  '其他': 'Others',
  '信息': 'Information',
  '个性化配置': 'Personalization',
  '首页': 'Home',
  '日程': 'Schedule',
  '服务': 'Services',
  '编辑(附加产品)': 'Edit (Ancillary Products)',
  '编辑(销售舱房配置)': 'Edit (Sales Cabin Config)',
  '编辑(预订配置)': 'Edit (Booking Config)',
  '切舱管理': 'Cabin Allocation Management',
  '切舱': 'Cabin Allocation',
  '直销概览': 'Direct Sales Overview',
  '代理概览': 'Agency Overview',
  '代理商管理': 'Agency Management',
  '代理商分类': 'Agency Classification',
  '代理商档案': 'Agency Profile',
  '编辑(旅客信息配置)': 'Edit (Guest Info Config)',
  '编辑(说明维护)': 'Edit (Notes Maintenance)',
  '编辑(旅客票据合同)': 'Edit (Guest Ticket Contract)',
  '编辑(基本信息)': 'Edit (Basic Info)',
  '编辑(联系人)': 'Edit (Contacts)',
  '编辑(代理商账号)': 'Edit (Agency Account)',
  '编辑(资金明细)': 'Edit (Fund Details)',
  '编辑(开票信息)': 'Edit (Invoice Info)',
  '编辑(变更日志)': 'Edit (Change Log)',
  '复制': 'Copy',
  '发布/停止发布': 'Publish/Unpublish',
  '旅客票据合同': 'Guest Ticket Contract',
  '订单审核': 'Order Review',
  '切舱申请': 'Cabin Allocation Application',
  '驳回': 'Reject',
  '系统信息维护': 'System Info Maintenance',
  '企业信息': 'Company Info',
  '软件信息': 'Software Info',
  '技术支持信息': 'Technical Support Info',
  '版本信息': 'Version Info',
  'IT维护': 'IT Maintenance',
  '企业授权信息': 'Enterprise License Info',
  '授权激活': 'License Activation',
  '服务条款': 'Terms of Service',
  '订单管理': 'Order Management',
  '散客订单': 'FIT Orders',
  '团队订单': 'Group Orders',
  '排房管理': 'Cabin Assignment Management',
  '旅客信息管理': 'Guest Information Management',
  '详情(基本信息)': 'Details (Basic Info)',
  '详情(预订信函)': 'Details (Booking Letter)',
  '详情(值船/船票)': 'Details (Check-in/Ticket)',
  '详情(交易流水)': 'Details (Transactions)',
  '详情(修改记录)': 'Details (Change Log)',
  '详情(发票信息)': 'Details (Invoice Info)',
  '详情(切舱信息)': 'Details (Allocation Info)',
  '详情(旅客名单)': 'Details (Guest List)',
  '详情(附加产品)': 'Details (Ancillary Products)',
  '导出人员信息': 'Export Passenger Info',
  '导出船票': 'Export Tickets',
  '导出对账单': 'Export Statement',
  '详情(乘客基础信息)': 'Details (Guest Basic Info)',
  '详情(医疗表格)': 'Details (Medical Form)',
  '详情(衣服靴子尺寸)': 'Details (Clothing & Boot Sizes)',
  '详情(到达/离开信息)': 'Details (Arrival/Departure Info)',
  '财务管理': 'Finance Management',
  '收款确认': 'Payment Confirmation',
  '代理商年度奖励统计': 'Agent Annual Incentive Statistics',
  '申请管理': 'Application Management',
  '无损退订申请': 'Penalty-Free Cancellation Application',
  '优惠价格申请': 'Discount Price Application',
  '更换出行人申请': 'Guest Change Application',
  '审批': 'Approval',
  '预存款审核': 'Deposit Review',
  '账单管理': 'Bill Management',
  '退订退款审核': 'Cancellation Refund Review',
  '退票审核': 'Ticket Refund Review',
  '退附加产品审核': 'Ancillary Service Refund Review',
  '预订管理': 'Booking Management',
  'KOL管理': 'KOL Management',
  'KOL名单': 'KOL List',
  'KOL订单': 'KOL Orders',
  '会员管理': 'Member Management',
  '会员管理(船端)': 'Member Management (Onboard)',
  '积分管理': 'Points Management',
  '积分规则': 'Points Rules',
  '积分商品': 'Points Goods',
  '兑换记录': 'Redemption Records',
  '券码核销': 'Coupon Verification',
  '团队支付按钮': 'Team Payment Button',
  '转会员': 'Convert to Member',
  '撤销转会员': 'Revoke Member Conversion',
  '分组：列表': 'Group: List',
  '分组：详情': 'Group: Details',
  '分组：新增': 'Group: Add',
  '分组：修改': 'Group: Edit',
  '分组：删除': 'Group: Delete',
  '分组：排序': 'Group: Sort',
  '语言：列表': 'Language: List',
  '语言：详情': 'Language: Details',
  '语言：新增': 'Language: Add',
  '语言：修改': 'Language: Edit',
  '语言：删除': 'Language: Delete',
  '恢复': 'Restore',
  '置顶': 'Pin to Top',
  '修改状态': 'Change Status',
  '删除标签': 'Delete Tag',
  '浏览量': 'Page Views',
  '邮轮介绍': 'Cruise Introduction',
  '邮轮航程表': 'Sailing Schedule',
  '活动日程表': 'Activity Schedule',
  '甲板导视': 'Deck Guide',
  '航程模板': 'Itinerary Template',
  '活动模板': 'Activity Template',
  '修改排序': 'Change Order',
  '舱房列表': 'Cabin List',
  '修改序号': 'Change Sequence',
  '自定义字段：列表': 'Custom Fields: List',
  '自定义字段：详情': 'Custom Fields: Details',
  '自定义字段：修改': 'Custom Fields: Edit',
  '报名管理': 'Registration Management',
  '活动报名名单': 'Activity Sign-up List',
  '活动资格认证': 'Activity Qualification',
  '添加名单': 'Add to List',
  '取消名单': 'Remove from List',
  '参与确认': 'Participation Confirmation',
  '船票退订': 'Ticket Cancellation',
  '附加产品退订': 'Ancillary Service Cancellation',
  '乘客信息更改': 'Guest Info Change',
  'WiFi管理': 'WiFi Management',
  '账户管理': 'Account Management',
  '销户管理': 'Account Cancellation Management',
  '查询统计': 'Query & Statistics',
  '销售统计': 'Sales Statistics',
  '赠送统计': 'Gift Statistics',
  '套餐管理': 'Package Management',
  '基础配置': 'Basic Configuration',
  '规则映射组': 'Rule Mapping Group',
  '条款配置': 'Terms Configuration',
  '设置映射': 'Set Mapping',
  '开户': 'Open Account',
  '批量开户': 'Batch Open Account',
  '销户': 'Close Account',
  '删除答卷': 'Delete Questionnaire',
  '购物管理': 'Shopping Management',
  '服务点管理': 'Service Point Management',
  '产品分组管理': 'Product Group Management',
  '产品管理': 'Product Management',
  '新建': 'Create',
  '页面内容管理': 'Page Content Management',
  '站点信息管理': 'Site Info Management',
  '会员中心': 'Member Center',
  '信息内容管理': 'Content Management',
  '探险航线': 'Expedition Routes',
  '探险活动': 'Expedition Activities',
  '探险邮轮': 'Expedition Cruises',
  '66°优势': '66° Advantages',
  '关于66°': 'About 66°',
  '会员计划': 'Membership Program',
  '联系我们': 'Contact Us',
  '条款声明': 'Terms Statement',
  '宣传手册': 'Brochure',
  '站点信息': 'Site Info',
  '页脚管理': 'Footer Management',
  '航行地区': 'Sailing Regions',
  '表单咨询': 'Form Inquiry',
  '咨询单': 'Inquiry Form',
  '标签配置': 'Tag Configuration',
  '忠诚配置': 'Loyalty Configuration',
  '订阅项配置': 'Subscription Items Configuration',
  '忠诚会员配置': 'Loyalty Member Configuration',
  '船东会员配置': 'Shipowner Member Configuration',
  '推荐好友奖励': 'Refer-a-Friend Rewards',
  '说明配置': 'Instruction Configuration',
  '分销码管理': 'Promo Code Management',
  'KOL预订': 'KOL Booking',
  '优惠券管理': 'Coupon Management',
  '优惠券列表': 'Coupon List',
  '直客订单': 'Direct Customer Orders',
  '退款审核': 'Refund Review',
  'KOL申请管理': 'KOL Application Management',
  '批量排房': 'Bulk Cabin Assignment',
  '详情操作': 'Details Actions',
  '航次房态': 'Voyage Cabin Status',
  '优惠码核销统计报表': 'Coupon Redemption Report',
  '会员管理(岸端)': 'Member Management (Shore)',
  '调整积分': 'Adjust Points',
  '变更会员类型(转忠诚)': 'Change Member Type (to Loyalty)',
  '变更会员类型(转船东)': 'Change Member Type (to Shipowner)',
  '同步resco账单数据': 'Sync RESCO Billing Data',

  // From zh-cn/addition.txt
  '预订信息': 'Booking Info',
  '旅客名单': 'Passenger List',
  '交易流水': 'Transaction History',
  '预订人手机': 'Booker Mobile',
  '订单备注': 'Order Remarks',
  '护照': 'Passport',

  '数据正在处理，请勿重复提交': 'Data is being processed, please do not resubmit',
  '无效的会话，或者会话已过期，请重新登录。': 'Invalid session or session expired, please log in again.',
  '后端接口连接异常': 'Backend API connection error',
  '系统接口请求超时': 'System API request timed out',
  '正在下载数据，请稍候': 'Downloading data, please wait',
  '下载文件出现错误，请联系管理员！': 'Error downloading file, please contact the administrator!',


  // from add.txt
  '剩余(天)': 'Remaining (Days)',
  '逾期(天)': 'Overdue (Days)',
  '付款提醒(未来一个月)': 'Payment Reminder (Next Month)',
  '已预定舱房数': 'Number of Booked Cabins',
  '单次预定数限制': 'Booking Limit per Order',
  '成团所需舱房数': 'Cabins Required to Form Group',
  '少量': 'Limited',
  '即将售罄': 'Almost Sold Out',
  '充足': 'Sufficient',
  '售罄': 'Sold Out',
  '舱房总费用': 'Total Cabin Cost',
  '附加产品列表': 'Add-on Product List',
  '新增产品': 'Add Product',
  '批量删除': 'Batch Delete',
  '附加产品总费用': 'Total Add-on Product Cost',
  '确认预订': 'Confirm Booking',
  '添加旅客': 'Add Traveler',
  '是否设置包房': 'Set as Whole Cabin',
  '单铺': 'Single Berth',
  '申请拿舱': 'Apply for Allocation',
  '定金': 'Deposit',
  '尾款': 'Final Payment',
  '中期款': 'Mid-term Payment',
  '中期款1': 'Mid-term Payment1',
  '中期款2': 'Mid-term Payment2',
  '退订中': 'In Cancellation',
  '原始舱房价格': 'Original Cabin Price',
  '拿舱价格': 'Allocation Price',
  '佣金减免': 'Commission Deduction',
  '已驳回': 'Rejected',
  '产品价格': 'Product Price',
  '请选择要退订的舱房': 'Please select the cabin to cancel',
  '船票模板尚在制作中': 'Ticket template is still being created',
  '错误信息': 'Error Information',
  '发布失败': 'Publish Failed',
  '预订政策': 'Booking Policy',
  '附加产品退订政策': 'Add-on Product Cancellation Policy',
  '支付节点': 'Payment Milestone',
  '乘客信息修改政策': 'Passenger Info Change Policy',
  '船票退订政策': 'Ticket Cancellation Policy',
  '登船凭证规则': 'Boarding Voucher Rule',
  '免额政策': 'FOC Policy',
  '基础价格': 'Base Price',


}