export default {
    逾期订单提醒: 'Overdue Order Alert',
    '{count}条未处理': '{count} pending',
    直销预订: 'Direct Sales Booking',
    代理预订: 'Agency Booking',
    KOL预订: 'KOL Booking',
    订单号: 'Order No.',
    代理: 'Agency',
    直销: 'Direct',
    KOL: 'KOL',
    航次: 'Voyage',
    开航日期: 'Departure Date',
    逾期天数: 'Days Overdue',
    快速链接: 'Quick Links',
    本月: 'This Month',
    上个月: 'Last Month',
    下个月: 'Next Month',
    航次日历: 'Voyage Calendar',
    航次详情: 'Voyage Details',
    当日暂无航次开航: 'No voyage departing today',
    未开售: 'Not on Sale',
    售票中: 'On Sale',
    等待开航: 'Awaiting Departure',
    运行中: 'In Progress',
    已结航: 'Completed',
    航次编号: 'Voyage No.',
    在线值船开放时间: 'Online Check-in Opens',
    开航时间: 'Departure Time',
    结航时间: 'Arrival Time',
    开始售票时间: 'Ticket Sales Start',
    截止售票时间: 'Ticket Sales End',
    预订情况: 'Booking Status',
    '总预订(间)': 'Total Bookings (rooms)',
    房间预订: 'Room Booking',
    房间预订情况: 'Room Booking Status',
    '单位：人': 'Unit: persons',
    人数: 'Headcount',
}
