export default {
  '承运人/船名': 'Carrier / Ship Name',
  航次编号: 'Voyage Number',
  启航日期: 'Departure Date',
  始发港: 'Port of Origin',
  目的港: 'Port of Destination',
  航线行程: 'Itinerary',
  预订编号: 'Booking Reference',
  船舱楼层: 'Deck Number',
  船舱位置: 'Cabin Location',
  舱房类型: 'Cabin Type',
  房间号码: 'Room Number',
  '船票类型(个人)': 'Ticket Type (Individual)',
  '船票类型(团队)': 'Ticket Type (Group)',
  姓名: 'Name',
  '国家/地区': 'Country / Region',
  出生日期: 'Date of Birth',
  性别: 'Gender',
  旅客证件号: 'Travel Document Number',
  身份证号: 'ID Card Number',
  联系方式: 'Contact Information',
}
