export default {
  邮轮通管理后台: 'CruisePass Admin',
  通知: 'Notifications',
  个人中心: 'Profile',
  状态: 'Status',
  启用: 'Active',
  禁用: 'Inactive',
  新增: 'Add',
  编辑: 'Edit',
  删除: 'Delete',
  序号: 'No.',
  操作: 'Actions',
  否: 'No',
  是: 'Yes',
  '确认要启用该条记录吗?': 'Are you sure you want to enable this record?',
  '确认要禁用该条记录吗?': 'Are you sure you want to disable this record?',
  '确认要删除该条记录吗?': 'Are you sure you want to delete this record?',
  启用成功: 'Enabled successfully',
  禁用成功: 'Disabled successfully',
  删除成功: 'Deleted successfully',
  启用失败: 'Enable failed',
  禁用失败: 'Disable failed',
  删除失败: 'Delete failed',
  '保存失败，缺少必填项！': 'Save failed, required fields are missing!',
  基础信息: 'Basic Info',
  中文: 'Chinese',
  英文: 'English',
  返回: 'Back',
  保存: 'Save',
  确定: 'OK',
  取消: 'Cancel',
  重置: 'Reset',
  保存成功: 'Saved successfully',
  保存失败: 'Save failed',
  新增成功: 'Added successfully',
  修改成功: 'Updated successfully',
  导入: 'Import',
  邮轮: 'Cruise',
  复制: 'Copy',
  导出Excel: 'Export Excel',
  导出: 'Export',
  '是否确认导出所有数据?': 'Are you sure you want to export all data?',
  应用程序下载: 'App Download',
  散客订单: 'Individual Orders',
  团队订单: 'Group Orders',
  上传: 'Upload',
  搜索: 'Search',
  展开: 'Expand',
  系统提示: 'System Alert',
  '共 {total} 项': 'Total {total} items',
  删除数据: 'Delete Data',
  请输入: 'Please enter',
  请选择: 'Please select',
  '是否放弃当前填写的内容，并恢复为上一次保存的数据记录？': 'Discard current changes and revert to last saved data?',
  重置提醒: 'Reset Reminder',
  确定重置: 'Confirm Reset',
  '排序 (双击编辑)': 'Sort (double-click to edit)',
  提示: 'Hint',
}
