export default {
  // Tab & context-menu
  刷新页面: 'Refresh Page',
  关闭当前: 'Close Current',
  关闭其他: 'Close Others',
  关闭左侧: 'Close Left',
  关闭右侧: 'Close Right',
  全部关闭: 'Close All',

  // System centers
  系统设置管理: 'System Settings',
  用户管理: 'User Management',
  角色管理: 'Role Management',
  菜单管理: 'Menu Management',
  部门管理: 'Department Management',
  岗位管理: 'Position Management',
  字典管理: 'Dictionary Management',
  参数设置: 'Parameter Settings',
  通知公告: 'Notifications',
  日志管理: 'Log Management',
  操作日志: 'Operation Log',
  登录日志: 'Login Log',

  // Workbench & centers
  工作台: 'Workbench',
  邮轮系统管理中心: 'Cruise System Management Center',
  邮轮数据配置中心: 'Cruise Data Configuration Center',
  邮轮系统运维中心: 'Cruise System Operations Center',
  邮轮接口文档中心: 'Cruise API Documentation Center',
  系统信息维护: 'System Information Maintenance',
  流程菜单: 'Process Menu',
  我的OA: 'My OA',
  待办任务: 'Pending Tasks',
  审批记录: 'Approval History',
  抄送我的: 'CC to Me',
  我的已办: 'Completed by Me',
  我的申请: 'My Applications',

  // Voyage & route
  航程配置管理: 'Voyage Configuration',
  航线管理: 'Route Management',
  航次管理: 'Voyage Management',
  切换航次: 'Switch Voyage',
  切换日期: 'Switch Date',
  基础数据配置: 'Basic Data Configuration',
  '位置/港口管理': 'Location / Port Management',
  船队管理: 'Fleet Management',
  甲板管理: 'Deck Management',
  舷梯管理: 'Gangway Management',
  清洁区域管理: 'Cleaning Area Management',
  舱房类型管理: 'Cabin Type Management',
  舱房管理: 'Cabin Management',
  '公司/组织管理': 'Company / Organization Management',
  邮轮部门管理: 'Cruise Department Management',
  旅游团管理: 'Tour Group Management',
  年龄组管理: 'Age Group Management',
  位置信息: 'Location Info',
  清洁区域划分: 'Cleaning Area Division',
  语言信息: 'Language Info',
  舷梯配置: 'Gangway Configuration',
  部门信息: 'Department Info',
  邮轮部门信息: 'Cruise Department Info',
  旅游团信息: 'Tour Group Info',
  年龄组信息: 'Age Group Info',
  甲板信息: 'Deck Info',
  舱房信息: 'Cabin Info',
  航线信息: 'Route Info',
  航次信息: 'Voyage Info',

  // Product & pricing
  产品配置管理: 'Product Configuration',
  景点管理: 'Attraction Management',
  基础价格: 'Base Price',
  优惠价格方案: 'Discount Scheme',
  代理商档案: 'Agency Profile',
  邮轮详情: 'Cruise Details',
  舱房等级详情: 'Cabin Grade Details',
  船舱信息详情: 'Cabin Details',
  港口详情: 'Port Details',
  证件详情: 'Document Details',
  说明维护: 'Description Maintenance',
  旅客票据合同: 'Passenger Ticket Contract',
  支付节点配置: 'Payment Milestone Configuration',
  船票退订规则: 'Ticket Cancellation Rules',
  附加产品退订规则: 'Add-on Cancellation Rules',
  促销规则: 'Promotion Rules',
  付款提醒: 'Payment Reminder',
  推送模板: 'Push Template',
  年龄模板: 'Age Template',
  出行证件: 'Travel Document',
  注意事项配置: 'Important Notice Configuration',

  // Forms & editing
  '新增/编辑问卷调查': 'Add / Edit Survey',
  '新增/编辑公告': 'Add / Edit Announcement',
  '新增/编辑事件反馈': 'Add / Edit Event Feedback',
  '新增/编辑公开标签': 'Add / Edit Public Tag',
  '新增/编辑内部标签': 'Add / Edit Internal Tag',
  '新增/编辑LOGO资源': 'Add / Edit Logo Resource',
  '新增/编辑图片资源': 'Add / Edit Image Resource',
  '新增/编辑视频资源': 'Add / Edit Video Resource',
  '新增/编辑甲板导视': 'Add / Edit Deck Signage',
  '新增/编辑功能条款': 'Add / Edit Terms & Conditions',
  '新增/编辑提示引用': 'Add / Edit Hint Reference',
  '新增/编辑航程模板': 'Add / Edit Voyage Template',
  '新增/编辑活动模板': 'Add / Edit Activity Template',
  '新增/编辑帮助须知': 'Add / Edit Help Notice',
  '新增/编辑自定义栏目': 'Add / Edit Custom Column',

  // Cruise operations
  邮轮航次: 'Cruise Voyage',
  邮轮管理: 'Cruise Management',
  前端内容管理: 'Frontend Content Management',
  紧急推送: 'Emergency Push',
  前端管理: 'Frontend Management',
  娱乐信息: 'Entertainment Info',
  资源库: 'Resource Library',
  资源详情: 'Resource Details',
  标签管理: 'Tag Management',
  事件管理: 'Event Management',
  问卷调查: 'Survey',
  配置: 'Configuration',
  展开菜单: 'Expand Menu',
  退出登录: 'Logout',
  邮轮航次管理: 'Cruise Voyage Management',

  // Emergency drill
  账户消费限制: 'Account Spending Limit',
  紧急集合控制台: 'Emergency Muster Console',
  开始演习: 'Start Drill',
  紧急撤离参数设置: 'Evacuation Parameter Settings',
  开始紧急撤船: 'Start Emergency Evacuation',
  可容纳人数: 'Capacity',
  需签到人数: 'Required Check-in',
  已签到人数: 'Checked-in',
  未签到人数: 'Not Checked-in',
  非本集合点签到人数: 'Checked-in at Wrong Station',
  在其他集合点签到人数: 'Checked-in at Other Stations',
  完成进度: 'Completion Progress',
  是否确认完成: 'Confirm Completion?',
  完成演习提醒: 'Drill Completion Reminder',
  开始: 'Start',
  演习中断提醒: 'Drill Interruption Reminder',
  '当前有演习正在进行中，是否终止并开始新的演习/紧急撤船': 'A drill is in progress. Terminate and start a new drill/emergency evacuation?',
  系统工具: 'System Tools',

  // Misc menus
  收件箱: 'Inbox',
  规则设置: 'Rule Settings',
  虚拟组件: 'Virtual Component',
  语言: 'Language',
  系统排版参考: 'System Layout Reference',
  航线设置: 'Route Settings',
  切舱管理: 'Cabin Allocation Management',
  代理概览: 'Agency Overview',
  产品设置: 'Product Settings',
  预订详情: 'Booking Details',
  值船信息: 'Check-in Info',
  值船办理: 'Check-in Process',
  乘客详情: 'Passenger Details',
  通行限制详情: 'Access Restriction Details',
  消息提示详情: 'Message Alert Details',
  演习详情: 'Drill Details',

  // ag-grid
  分页: 'Pagination',
  每页条数: 'Rows per page',
  行高: 'Row Height',
  高度: 'Height',
  表头高度: 'Header Height',
  表项高度: 'Item Height',
  恢复默认: 'Restore Default',
  自动高度: 'Auto Height',
  固定高度: 'Fixed Height',

  // copyright
  折叠菜单: 'Collapse Menu',
}
