export default {
  project: {
    enterprise: {
      客户企业信息: 'Client Enterprise Information',
      软件企业信息: 'Software Enterprise Information',
      企业LOGO: 'Company Logo',
      企业全称: 'Company Full Name',
      请输入企业全称: 'Please enter the company full name',
      启用显示: 'Enable Display',
      企业LOGO不能为空: 'Company logo is required',
      企业全称不能为空: 'Company full name is required',
    },
    software: {
      登录页: 'Login Page',
      使用显示: 'Use Display',
      系统图标: 'System Icon',
      系统名称: 'System Name',
      '宽不限,高32': 'Any width, height 32 px',
      系统次文: 'System Subtitle',
      系列: 'Series',
      请输入系统名称: 'Please enter the system name',
      请输入系统次文: 'Please enter the system subtitle',
      版权信息: 'Copyright Information',
      请输入版权信息: 'Please enter the copyright information',
      登录页插图: 'Login Page Illustration',
      登录页背景: 'Login Page Background',
      使用显示不能为空: 'Use display is required',
      系统图标不能为空: 'System icon is required',
      系统名称不能为空: 'System name is required',
      版权信息不能为空: 'Copyright information is required',
      登录页插图不能为空: 'Login page illustration is required',
      登录页背景不能为空: 'Login page background is required',
      显示客户企业全称不能为空: 'Display client company full name is required',
      显示模块名称不能为空: 'Display module name is required',
      显示客户企业全称: 'Display client company full name',
      显示模块名称: 'Display module name',
      系统内: 'System Internal',
    },
    support: {
      技术支持信息: 'Technical Support Information',
      启用显示: 'Enable Display',
      信息显示: 'Information Display',
      请输入信息显示: 'Please enter the information to display',
      信息显示不能为空: 'Information display is required',
      服务条款: 'Terms of Service',
      跳转链接: 'Redirect Link',
      标题: 'Title',
      链接: 'Link',
      启用状态: 'Enable Status',
      请输入标题: 'Please enter the title',
      请输入链接: 'Please enter the link',
      标题不能为空: 'Title is required',
      链接不能为空: 'Link is required',
    },
    version: {
      软件信息: 'Software Information',
      系统版本: 'System Version',
      请输入系统版本: 'Please enter the system version',
      系统版本不能为空: 'System version is required',
    },
  },
}
